#version 460
#extension GL_EXT_buffer_reference : require
#extension GL_EXT_scalar_block_layout : require
#extension GL_EXT_shader_explicit_arithmetic_types_int16 : require
#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require

#include "common/geometry.glsl"
#include "common/camera.glsl"
#include "common/instances.glsl"

layout(local_size_x = 64) in;

layout(buffer_reference, scalar) buffer VisibleInstanceBuffer { uint count; uint data[]; };

layout(push_constant) uniform Push {
    CameraBuffer camera;
    GeometryBuffer geometry;
    InstanceBuffer instances;
    TransformBuffer transforms;
    VisibleInstanceBuffer visible_instances;
    uint instance_count;
} pc;

void main() {
    uint id = gl_GlobalInvocationID.x;
    if (id >= pc.instance_count) return;

    Instance instance = pc.instances.data[id];
    mat4 model = pc.transforms.data[instance.transform_id].curr_mtx;
    Mesh mesh = pc.geometry.meshes.data[instance.mesh_id];

    vec3 center = (model * vec4(mesh.bounds_sphere.xyz, 1.0)).xyz;
    float scale = transform_max_scale(model);
    float radius = mesh.bounds_sphere.w * scale;

    if (frustum_cull_sphere(pc.camera, center, radius)) return;
    
    uint slot = atomicAdd(pc.visible_instances.count, 1u);
    pc.visible_instances.data[slot] = id;
}